apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: pubsub-receiver
  name: pubsub-receiver
  namespace: default
spec:
  replicas: 1
  minReadySeconds: 45
  selector:
    matchLabels:
      app: pubsub-receiver
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: pubsub-receiver
    spec:
      containers:
      - image: luisorellanaa/pubsub-receiver:0.0.1-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: pubsub-receiver
        env:
          - name: FIRESTORE_URI
            value: http://firestore  
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: pubsub-receiver
  name: pubsub-receiver
  namespace: default
spec:
  ports:
  - 
    port: 8082
    protocol: TCP
    targetPort: 8082
  selector:
    app: pubsub-receiver
  sessionAffinity: None
  type: NodePort
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: pubsub-receiver
  namespace: default
spec:
  maxReplicas: 3
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: pubsub-receiver
  targetCPUUtilizationPercentage: 10