apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: firestore
  name: firestore
  namespace: default
spec:
  replicas: 1
  minReadySeconds: 45
  selector:
    matchLabels:
      app: firestore
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: firestore
    spec:
      containers:
      - image: luisorellanaa/firestore:0.0.1-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: firestore      
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: firestore
  name: firestore
  namespace: default
spec:
  ports:
  - 
    port: 8083
    protocol: TCP
    targetPort: 8083
  selector:
    app: firestore
  sessionAffinity: None
  type: NodePort
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: firestore
  namespace: default
spec:
  maxReplicas: 3
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: firestore
  targetCPUUtilizationPercentage: 10