apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: pubsub-sender
  name: pubsub-sender
  namespace: default
spec:
  replicas: 1
  minReadySeconds: 45
  selector:
    matchLabels:
      app: pubsub-sender
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: pubsub-sender
    spec:
      containers:
      - image: luisorellanaa/pubsub-sender:0.0.1-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: pubsub-sender
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: pubsub-sender
  name: pubsub-sender
  namespace: default
spec:
  ports:
  - nodePort: 31057
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: pubsub-sender
  sessionAffinity: ClientIP
  type: LoadBalancer
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: pubsub-sender
  namespace: default
spec:
  maxReplicas: 2
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: pubsub-sender
  targetCPUUtilizationPercentage: 10